---
- name: Download oc
  ansible.builtin.unarchive:
    src: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/{{ redhat_oc_version }}/openshift-client-linux.tar.gz"
    include: oc
    dest: '{{ redhat_bin_dir }}'
    remote_src: yes
  register: redhat_srep_oc

- name: oc completion
  ansible.builtin.command: "bash -lc '{{ redhat_bin_dir }}/oc completion {{ redhat_completion_shell }} > {{ redhat_completion_dir }}/oc-completion'"
  when: redhat_srep_oc.changed and redhat_add_completion

- name: Download ocm
  get_url:
    url: "https://github.com/openshift-online/ocm-cli/releases/download/v{{ redhat_ocm_version }}/ocm-linux-amd64"
    dest: '{{ redhat_bin_dir }}/ocm'
    mode: '0755'
  register: redhat_srep_ocm

- name: ocm completion
  ansible.builtin.command: "bash -lc '{{ redhat_bin_dir }}/ocm completion {{ redhat_completion_shell }} > {{ redhat_completion_dir }}/ocm-completion'"
  when: redhat_srep_ocm.changed and redhat_add_completion

- name: Download osdctl
  ansible.builtin.unarchive:
    src: "https://github.com/openshift/osdctl/releases/download/v{{ redhat_osdctl_version }}/osdctl_{{ redhat_osdctl_version }}_Linux_x86_64.tar.gz"
    include: osdctl
    dest: '{{ redhat_bin_dir }}'
    remote_src: yes
  register: redhat_srep_osdctl

- name: osdctl completion
  ansible.builtin.command: "bash -lc '{{ redhat_bin_dir }}/osdctl completion {{ redhat_completion_shell }} > {{ redhat_completion_dir }}/osdctl-completion'"
  when: redhat_srep_osdctl.changed and redhat_add_completion

- name: Download rosa
  get_url:
    url: "https://github.com/openshift/rosa/releases/download/v{{ redhat_rosa_version }}/rosa-linux-amd64"
    dest: '{{ redhat_bin_dir }}/rosa'
    mode: '0755'
  register: redhat_srep_rosa

- name: rosa completion
  ansible.builtin.command: "bash -lc '{{ redhat_bin_dir }}/rosa completion {{ redhat_completion_shell }} > {{ redhat_completion_dir }}/rosa-completion'"
  when: redhat_srep_rosa.changed and redhat_add_completion

- name: Download ocm-container-v2
  ansible.builtin.unarchive:
    src: "https://github.com/iamkirkbater/ocm-container-v2/releases/download/v{{ redhat_ocm_container_version }}/ocm-container-v2_{{ redhat_ocm_container_version }}_Linux_x86_64.tar.gz"
    include: ocm-container-v2
    dest: '{{ redhat_bin_dir }}'
    remote_src: yes
  register: redhat_srep_occ

- name: occ completion
  ansible.builtin.command: "bash -lc '{{ redhat_bin_dir }}/ocm-container-v2 completion {{ redhat_completion_shell }} > {{ redhat_completion_dir }}/ocm-container-v2-completion'"
  when: redhat_srep_occ.changed and redhat_add_completion

- name: Download ocm backplane
  ansible.builtin.unarchive:
    src: "https://github.com/openshift/backplane-cli/releases/download/v{{ redhat_backplane_version }}/ocm-backplane_{{ redhat_backplane_version }}_Linux_x86_64.tar.gz"
    include: ocm-backplane
    dest: '{{ redhat_bin_dir }}'
    remote_src: yes
  register: redhat_srep_ocm_backplane

- name: ocm-backplane completion
  ansible.builtin.command: "bash -lc '{{ redhat_bin_dir }}/ocm-backplane completion {{ redhat_completion_shell }} > {{ redhat_completion_dir }}/ocm-backplane-completion'"
  when: redhat_srep_ocm_backplane.changed and redhat_add_completion

- name: install oc-nodepp
  ansible.builtin.unarchive:
    src: "https://github.com/mrbarge/oc-nodepp/releases/download/v{{ redhat_oc_nodepp_version }}/oc-nodepp_Linux_x86_64.tar.gz"
    include: oc-nodepp
    dest: '{{ tools_bin_dir }}'
    remote_src: yes
  register: tools_oc_nodepp
